### ISSUE TITLE
XBee Thread

### ISSUE THREAD

**Issue by mbrunnen** [nioinnovation/python-xbee#11]
Hi,
Digi will release soon a module with Thread support:
[http://www.digi.com/resources/standards-and-technologies/thread-networking-protocol](url)

I also found digi datasheet where they are talking about "thread ready":
https://www.gamma.pl/sklep/img/cms/digi/ds_xbee_zigbee_thread.pdf

There's already an open source implementation of thread here on github:
[https://github.com/openthread/openthread](url)

I hope you're considering to support this :)

**Comment by hansmosh** [comment]
No owner of this repo is planning on implementing Thread support when that is released, but we are here to discuss ideas and accept pull requests.
