### ISSUE TITLE
ZigBee TX frame composition

### ISSUE THREAD

**Issue by alexandra111** [nioinnovation/python-xbee#13]
Hi.

I am trying to develop some code in order to send TX frame. I am new to Python, but I have worked before with XBees in C++ without bigger problems. I am using XBee DigiMesh modules and I declared them as ZigBee objects in the code. Could you please explain me, what am I doing wrong? Unfortunately I get SyntaxError in xbee.send(). 

```
from xbee import ZigBee
ser = serial.Serial("7dev7ttyACM0", 9600)
xbee = ZigBee(ser)

 xbee.send('tx',{ 'id'=1, 'frame_id'=1, 'dest_addr_long' = b'\x00\x00\x00\x00\x00\x00\xFF\xFF', 'dest_addr'=b'\xFF\xFE', 'options'=b'\xFF\xFE', 'data'=string })
```

I am working on Raspberry Pi B

**Comment by hohenstaufen** [comment]
Works fine with this syntax:
```
xbee.send('tx', dest_addr_long=b'\x00\x00\x00\x00\x00\x00\xFF\xFF', dest_addr=b'\xFF\xFE', data=b'data')
```

**Comment by hansmosh** [comment]
@hohenstaufen's solution looks good to me.
