### ISSUE TITLE
No second answer after one successful conversation with encryption

### ISSUE THREAD

**Issue by mbrunnen** [nioinnovation/python-xbee#31]
Hi,
Sorry, I'm in a hurry so a brief description.
When I have encryption enabled (EE) in XCTU: 
I can only have one successful data exchange. That means the receiver, which is a router, receives and replies sucessfully. When I try the same operation again, without restarting the receiver, the receiver don't get any frames at all afterwards. When the receiver is a coordinator everything's fine.
When EE is 0 everything works fine. It's maybe a digi bug, but I just wanted to let you know.
I'm using XB24D
My Best

**Comment by jamesleesaunders** [comment]
Did you ever get a conclusion to this? Is this still an issue?

**Comment by mbrunnen** [comment]
As far as I remember it was a firmware problem.
