### ISSUE TITLE
API-mode tx frame

### ISSUE THREAD

**Issue by almeidaErick** [nioinnovation/python-xbee#33]
When I send a frame from python "tx frame" to another digimesh connected using XCTU to check the received packets, from 10 packets sent only arrives 1. Please help me with that if I am forgetting to sent any API command or something.
NOTE: I tested both digimesh using XCTU and both can receive and send packets correctly, so it must be the API in python the problem, but I have no idea what.

this is my tx frame
xbee.send("tx", frame_id="G", dest_addr=destination, data=message)

destination: the destination address
data: the message to be sent (ASCII)

**Comment by jamesleesaunders** [comment]
Did you ever get a conclusion to this? Is this still an issue?

**Comment by BenTheNinjaRock** [comment]
If your message to be sent exceeds the maximum payload (which can be found in XCTU) the packet will be dropped. Maybe that's it?
