### ISSUE TITLE
Digimesh Library default values should be bytes

### ISSUE THREAD

**Issue by killian441** [nioinnovation/python-xbee#45]
For Python3 the digimesh module fails if given the defaults because they are currently strings and not bytes.

**Comment by jamesleesaunders** [comment]
Hi @killian441 thanks for raising. Please do feel to fork/raise pull request if you have a proposed fix. Contributions are always welcome :-)

**Comment by jamesleesaunders** [comment]
I have added Python 3 support to the DigiMesh class on PR #46. 
Feel free to give it a test by cloning this branch while we wait for it to be approved to be merged with master:
https://github.com/nioinnovation/python-xbee/tree/issue45-digimesh-p3

**Comment by killian441** [comment]
Hi, thanks for putting together a pull-request. I had planned to do one when I had some free time, but this is all I would do. Looks good

**Comment by jamesleesaunders** [comment]
No problem., this was a fairly simple one :-). Please do feel free to contribute if you see anything else amiss. This has now been merged in DigiMesh should now work with Python 3.
Jim
